version: '3'
services:
  app:
    build: .
    ports:
      - "8000:8000"
      - 3000:3000
    volumes:
      - "./:/app"
    networks:
      - app-network

  db:
    image: mongo
    ports:
      - "27018:27018"
    volumes:
      - db-data:/data/db
    networks:
      - app-network
volumes:
  db-data:
networks:
  app-network:

